### PR TITLE
Drone example added

### PR DESCRIPTION
**Pull request by phisco**
Finally managed to strip down our drone pipeline to a self contained example, any suggestion on how to improve it is welcome.

### CODE REVIEW

**Comment by tao12345666333** [comment]
LGTM. 

Thanks. 

We can run it using https://cloud.drone.io/ to verify the results.

**Comment by phisco** [comment]
It seems to not be possible to have a trusted pipeline using https://cloud.drone.io/, for obvious security reasons being the runners shared (as stated [here](https://discourse.drone.io/t/solved-running-in-privileged-mode/3736/4)). 
Although I have tested the pipeline using our own private Drone installation.

**Comment by phisco** [comment]
Notice that I haven’t added the ✅ to the main README, didn’t know if some requirements had to be matched before doing so

**Comment by BenTheElder** [comment]
ah, thanks, let me update that... we still need to figure out the right format there. I think for ones running in this repo we should include the badge to distinguish.

**Comment by BenTheElder** [comment]
I updated it with a check etc.

**Comment by BenTheElder** [comment]
and thanks again! 🙃

**Pull request merged**
